from enum import Enum, auto


class PropertyCode(Enum):
    """
    Enum representing all the linear material properties that can be assigned. For more details see
    :meth:`~ansys.mapdl.core._commands._preproc.materials.mplist`.
    """

    EX = auto()
    EY = auto()
    EZ = auto()
    ALPX = auto()
    ALPY = auto()
    ALPZ = auto()
    CTEX = auto()
    CTEY = auto()
    CTEZ = auto()
    THSX = auto()
    THSY = auto()
    THSZ = auto()
    REFT = auto()
    PRXY = auto()
    PRYZ = auto()
    PRXZ = auto()
    NUXY = auto()
    NUYZ = auto()
    NUXZ = auto()
    GXY = auto()
    GYZ = auto()
    GXZ = auto()
    DAMP = auto()
    DMPR = auto()
    MU = auto()
    DENS = auto()
    C = auto()
    ENTH = auto()
    KXX = auto()
    KYY = auto()
    KZZ = auto()
    HF = auto()
    EMIS = auto()
    QRATE = auto()
    VISC = auto()
    SONC = auto()
    RSVX = auto()
    RSVY = auto()
    RSVZ = auto()
    PERX = auto()
    PERY = auto()
    PERZ = auto()
    MURX = auto()
    MURY = auto()
    MURZ = auto()
    MGXX = auto()
    MGYY = auto()
    MGZZ = auto()
    LSSM = auto()
    LSST = auto()
    SBKX = auto()
    SBKY = auto()
    SBKZ = auto()
