- name: BLOCKER
  description: No further development until this is fixed.
  color: 000000

- name: BUG
  description: ""
  color: 994d00

- name: CI/CD
  description: ""
  color: b5f226

- name: Critical Priority
  description: ""
  color: ff0000

- name: Dependencies
  description: Dependencies
  color: a5db76

- name: Discussion
  description: ""
  color: bfdec3

- name: DO NOT MERGE
  description: ""
  color: 4f18e7

- name: Documentation
  description: ""
  color: bdd9db

- name: Duplicate
  description: ""
  color: cccccc

- name: Enhancement
  description: Improve any current implemented feature.
  color: 80b5ea

- name: Examples
  description: ""
  color: bfdec3

- name: Future
  description: To work on it in the future.
  color: c2ddf4

- name: Good First Issue
  description: Good and easy issue to start to work in PyANSYS development.
  color: f9cfc3

- name: Help wanted
  description: Tell the developers you need help or guidance.
  color: 12880c

- name: Maintenance
  description: Maintenance
  color: bbd2f1

- name: Major Priority
  description: ""
  color: ff7300

- name: MAPDL
  description: Requires changes in MAPDL
  color: 000000

- name: Minor Priority
  description: ""
  color: ffdd00

- name: New Feature
  description: Request/proposal for a new feature
  color: 235370

- name: Question
  description: ""
  color: c9317d

- name: Stale
  description: Stale issue, it will be closed.
  color: c106be

- name: Support
  description: ""
  color: 54afbb

- name: Won't fix
  description: ""
  color: ffffff

- name: reminder
  description: "Label for the reminder bot"
  color: c5def5

- name: Nightly build failed
  description: "Label for the nightly fails"
  color: b5f226