#############################################################
# Reason for this file
# ====================
#
# This file is used by labeler to sync the labels (and their colors),
# and assign a label to the new pull requrest.
# 
# Check the yml for more info: .github\workflows\label.yml

#############################################################
# Main colors (hex)
# =================

# C0392B # Red: International Orange (Golden Gate Bridge)
# E67E22 # Orange: Vivid Tangelo
# F4D03F # Yellow: Sandstorm
# F9E79F # Light yellow: Medium champagne
# 27AE60 # Green: Green (Crayola)
# ffffff # White
# 2E86C1 # Dark blue: Cyan Cornflower Blue
# 85C1E9 # Light blue: Aero
# A569BD # Purple: Rich Lavender
# 76D7C4 # Light green: Pearl Aqua
# 000000 # Black

# https://htmlcolorcodes.com/ -- For color picking
# https://www.color-name.com/ -- For colors to names

#############################################################
# By priority
# ===========

- name: BLOCKER
  description: "No further development until this is fixed."
  color: C0392B # Red

- name: Critical Priority
  description: "This issue affects almost all users"
  color: E67E22 # Orange

- name: Major Priority
  description: "This issue affects some users"
  color: F4D03F # yellow

- name: Minor Priority
  description: "It does not affect almost any users"
  color: F9E79F # light yellow

- name: Future
  description: "To work on it in the future, since it can be delayed"
  color: 27AE60  # Green

- name: Won't fix
  description: "For different reasons, this won't be fixed"
  color: ffffff # white

#############################################################
# By Category
# ===========

- name: BUG
  description: ""
  color: E67E22

- name: New Feature
  description: Request or proposal for a new feature
  color: 2E86C1
  
- name: Enhancement
  description: Improve any current implemented feature.
  color: 85C1E9

- name: Examples
  description: ""
  color: A569BD

- name: Documentation
  description: ""
  color: A569BD

- name: Maintenance
  description: Maintenance
  color: 76D7C4

- name: Discussion
  description: ""
  color: 76D7C4

- name: Question
  description: ""
  color: 76D7C4

#############################################################
# Context
# =======

- name: DO NOT MERGE
  description: ""
  color: C0392B

- name: Duplicate
  description: ""
  color: E67E22

- name: Good First Issue
  description: Good and easy issue to start to work in PyANSYS development.
  color: 27AE60

- name: Help wanted
  description: Tell the developers you need help or guidance.
  color: F4D03F

- name: Stale
  description: Stale issue, it will be closed.
  color: E67E22

#############################################################
# For repo maintance
# ==================

- name: CI/CD
  description: ""
  color: F9E79F

- name: Dependencies
  description: Dependencies
  color: F9E79F

- name: MAPDL
  description: Requires changes in MAPDL
  color: 000000

- name: reminder
  description: "Label for the reminder bot"
  color: ffffff

- name: Build failed
  description: "Label for the build fails"
  color: E67E22
