changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - new feature
    - title: Bug fixes or behavior changes
      labels:
        - bug
        - BLOCKER
    - title: Documentation
      labels:
        - documentation
        - examples
    - title: Maintenance
      labels:
        - maintenance
        - dependencies
        - CI/CD
    - title: MAPDL and/or API related
      labels:
        - MAPDL
