ignore:
  - "src/ansys/mapdl/core/_commands"
  - "src/ansys/mapdl/core/jupyter.py"
  - "src/ansys/mapdl/core/mapdl_console.py"
  - "src/ansys/mapdl/core/mapdl_corba.py"

comment:
  layout: "diff"
  behavior: default

coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 90%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
