/COM, DUCATI FRAME MODEL
/COM, ------------------------------------------------
/COM,

FINISH
/CLEAR,START
/PREP7
/NOPR
/TITLE, DUCATI FRAME MODEL FOR DCP

! OPTIMIZATION PARAMETERS
! -----------------------

! Optimization can develop three custom tubes with radius and thickness
*DIM,radius,ARRAY,3,1,1, , ,
radius(1)=14.0
radius(2)=15.0
radius(3)=5.0

*DIM,thickness,ARRAY,3,1,1, , ,
thickness(1)=1.0
thickness(2)=1.1
thickness(3)=1.0

! Optimization evaluates where to use the three custom tubes
num_tubes=21
*DIM,tubes,ARRAY,num_tubes,1
tubes(1)=1
tubes(2)=1
tubes(3)=3
tubes(4)=1
tubes(5)=1
tubes(6)=1
tubes(7)=1
tubes(8)=1
tubes(9)=1
tubes(10)=1
tubes(11)=3
tubes(12)=3
tubes(13)=1
tubes(14)=3
tubes(15)=2
tubes(16)=2
tubes(17)=3
tubes(18)=2
tubes(19)=3
tubes(20)=3
tubes(21)=1

! ELEMENT TYPES
! -------------
ET,  11  , BEAM188

! Key Options
! -----------

! Coordinate Systems
! ----------------

! No special coordinate systems defined

! TUBE SECTIONS
! -------------------
n=25
! Variable sections
*DO,i,1,num_tubes
	SECTYPE,   i, BEAM, CTUBE, , 0
	SECOFFSET, CENT
	SECDATA,radius(tubes(i))-thickness(tubes(i)),radius(tubes(i)),n,0,0,0,0,0,0,0,0,0
*ENDDO

! Steering tube
SECTYPE,   101, BEAM, CTUBE, , 0
SECOFFSET, CENT
SECDATA,37,40,n,0,0,0,0,0,0,0,0,0

! Engine stiffness
SECTYPE,   102, BEAM, CSOLID, , 0
SECOFFSET, CENT
SECDATA,6,n,0,0,0,0,0,0,0,0,0,0
SECTYPE,   103, BEAM, CSOLID, , 0
SECOFFSET, CENT
SECDATA,8,25,0,0,0,0,0,0,0,0,0,0


! NODES
! -----
NBLOCK,6,SOLID
(3i8,6e16.9)
       1       0       0 0.00000000      134.000000      0.00000000
       2       0       0 0.00000000      134.000000      96.0000000
       3       0       0 88.0000000      139.500000      295.000000
       4       0       0 57.0000000      137.500000      105.000000
       5       0       0 216.000000      147.500000      131.000000
       6       0       0 428.000000      161.000000      165.500000
       7       0       0 640.000000      161.000000      200.000000
       8       0       0 785.000000      0.00000000      205.000000
       9       0       0 354.000000      156.500000      0.00000000
      10       0       0 668.000000      161.000000      57.0000000
      11       0       0 785.000000      0.00000000      65.0000000
      12       0       0 407.000000      0.00000000      119.000000
      13       0       0 690.000000      0.00000000      60.0000000
      14       0       0 785.000000      0.00000000      44.0000000
      15       0       0 785.000000      0.00000000      135.000000
      16       0       0 785.000000      0.00000000      226.500000
      17       0       0 0.00000000      -134.000000     0.00000000
      18       0       0 0.00000000      -134.000000     96.0000000
      19       0       0 88.0000000      -139.500000     295.000000
      20       0       0 57.0000000      -137.500000     105.000000
      21       0       0 216.000000      -147.500000     131.000000
      22       0       0 428.000000      -161.000000     165.500000
      23       0       0 640.000000      -161.000000     200.000000
      24       0       0 354.000000      -156.500000     0.00000000
      25       0       0 668.000000      -161.000000     57.0000000
      26       0       0 0.00000000      90.0000000      0.00000000
      27       0       0 0.00000000      -90.0000000     0.00000000
      28       0       0 57.0000000      90.0000000      105.000000
      29       0       0 57.0000000      -90.0000000     105.000000
      30       0       0 354.000000      90.0000000      0.00000000
      31       0       0 264.610000      90.0000000      -166.830000
      32       0       0 264.610000      -90.0000000     -166.830000
      33       0       0 354.000000      -90.0000000     0.00000000
N,R5.3,LOC, -1,


! ELEMENTS
! --------
EBLOCK,19,SOLID
(19i7)
1      11     1      1      0      0      0      0      2      0      1      1      2
1      11     1      2      0      0      0      0      2      0      2      2      3
1      11     2      3      0      0      0      0      2      0      3      1      4
1      11     1      4      0      0      0      0      2      0      4      2      4
1      11     1      5      0      0      0      0      2      0      5      4      5
1      11     1      6      0      0      0      0      2      0      6      5      6
1      11     1      7      0      0      0      0      2      0      7      6      7
1      11     1      8      0      0      0      0      2      0      8      7      8
1      11     2      9      0      0      0      0      2      0      9      3      5
1      11     2      10     0      0      0      0      2      0      10     5      9
1      11     2      11     0      0      0      0      2      0      11     9      6
1      11     2      12     0      0      0      0      2      0      12     6      10
1      11     2      13     0      0      0      0      2      0      13     10     7
1      11     9      14     0      0      0      0      2      0      14     7      11
1      11     1      15     0      0      0      0      2      0      15     9      10
1      11     1      16     0      0      0      0      2      0      16     10     11
1      11     9      17     0      0      0      0      2      0      17     9      12
1      11     2      18     0      0      0      0      2      0      18     6      12
1      11     2      19     0      0      0      0      2      0      19     10     13
1      11     2      20     0      0      0      0      2      0      20     13     11
1      11     16     101    0      0      0      0      2      0      21     11     14
1      11     16     101    0      0      0      0      2      0      22     11     15
1      11     16     101    0      0      0      0      2      0      23     8      15
1      11     16     101    0      0      0      0      2      0      24     8      16
1      11     1      1      0      0      0      0      2      0      25     17     18
1      11     1      2      0      0      0      0      2      0      26     18     19
1      11     2      3      0      0      0      0      2      0      27     17     20
1      11     1      4      0      0      0      0      2      0      28     18     20
1      11     1      5      0      0      0      0      2      0      29     20     21
1      11     1      6      0      0      0      0      2      0      30     21     22
1      11     1      7      0      0      0      0      2      0      31     22     23
1      11     1      8      0      0      0      0      2      0      32     23     8
1      11     2      9      0      0      0      0      2      0      33     19     21
1      11     2      10     0      0      0      0      2      0      34     21     24
1      11     2      11     0      0      0      0      2      0      35     24     22
1      11     2      12     0      0      0      0      2      0      36     22     25
1      11     2      13     0      0      0      0      2      0      37     25     23
1      11     9      14     0      0      0      0      2      0      38     23     11
1      11     1      15     0      0      0      0      2      0      39     24     25
1      11     1      16     0      0      0      0      2      0      40     25     11
1      11     9      17     0      0      0      0      2      0      41     24     12
1      11     2      18     0      0      0      0      2      0      42     22     12
1      11     2      19     0      0      0      0      2      0      43     25     13
1      11     1      21     0      0      0      0      2      0      44     3      19
2      11     17     103    0      0      0      0      2      0      45     26     27
2      11     17     103    0      0      0      0      2      0      46     26     28
2      11     17     103    0      0      0      0      2      0      47     26     29
2      11     17     103    0      0      0      0      2      0      48     26     30
2      11     17     103    0      0      0      0      2      0      49     26     31
2      11     17     103    0      0      0      0      2      0      50     26     32
2      11     17     103    0      0      0      0      2      0      51     27     28
2      11     17     103    0      0      0      0      2      0      52     27     29
2      11     17     103    0      0      0      0      2      0      53     27     33
2      11     17     103    0      0      0      0      2      0      54     27     31
2      11     17     103    0      0      0      0      2      0      55     27     32
2      11     17     103    0      0      0      0      2      0      56     28     29
2      11     17     103    0      0      0      0      2      0      57     28     30
2      11     17     103    0      0      0      0      2      0      58     28     33
2      11     17     103    0      0      0      0      2      0      59     28     31
2      11     17     103    0      0      0      0      2      0      60     29     30
2      11     17     103    0      0      0      0      2      0      61     29     33
2      11     17     103    0      0      0      0      2      0      62     29     32
2      11     17     103    0      0      0      0      2      0      63     30     33
2      11     17     103    0      0      0      0      2      0      64     30     31
2      11     17     103    0      0      0      0      2      0      65     30     32
2      11     17     103    0      0      0      0      2      0      66     33     31
2      11     17     103    0      0      0      0      2      0      67     33     32
2      11     17     103    0      0      0      0      2      0      68     31     32
1      11     18     102    0      0      0      0      2      0      69     1      26
1      11     18     102    0      0      0      0      2      0      70     17     27
1      11     18     102    0      0      0      0      2      0      71     4      28
1      11     18     102    0      0      0      0      2      0      72     20     29
1      11     18     102    0      0      0      0      2      0      73     9      30
1      11     18     102    0      0      0      0      2      0      74     24     33
-1

! MATERIALS
! ---------
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,EX,1      , 1, 210000.000
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,PRXY,1      , 1, 0.300000000
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,DENS,1      , 1, 7.85000000e-09
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,EX,2      , 1, 70000.0000
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,PRXY,2      , 1, 0.300000000
MPTEMP,R5.0, 1, 1, 0. ,
MPDATA,R5.0, 1,DENS,2      , 1, 2.70000000e-09

! BOUNDARY CONDTIONS
! ------------------
D,1      ,UX  ,0.00000000
D,1      ,UY  ,0.00000000
D,1      ,UZ  ,0.00000000
D,15     ,UZ  ,0.00000000
D,17     ,UX  ,0.00000000
D,17     ,UY  ,0.00000000
D,17     ,UZ  ,0.00000000

FINISH
/SOLU
! TORSION LOADCASE
M_torsion=700000.000
F,15     ,MX  ,M_torsion
SOLVE

/POST1
SET,LAST

! v1 = C2 + U2 - (C1 + U1)
n1=1
n2=17
*VEC,v1,D,ALLOC,3
!*DIM,v1,ARRAY,3,1
v1(1) = NX(n2) + UX(n2) - (NX(n1)+UX(n1) )
v1(2) = NY(n2) + UY(n2) - (NY(n1)+UY(n1) )
v1(3) = NZ(n2) + UZ(n2) - (NZ(n1)+UZ(n1) )

! v2 = C2 + U2 - (C1 + U1)
n1=14
n2=16
*VEC,v2,D,ALLOC,3
!*DIM,v2,ARRAY,3,1
v2(1) = NX(n2) + UX(n2) - (NX(n1)+UX(n1) )
v2(2) = NY(n2) + UY(n2) - (NY(n1)+UY(n1) )
v2(3) = NZ(n2) + UZ(n2) - (NZ(n1)+UZ(n1) )

! double twist = acos ( mtl::dot ( v1, v2 ) / ( mtl::two_norm( v1 ) * two_norm( v2 ) ) );
*DOT,v1,v2,dot_v1v2
*NRM,v1,NRM2,v1n
*NRM,v2,NRM2,v2n
twist=acos(dot_v1v2/(v1n*v2n))
PI=acos(-1)
! Twist in degrees, minus 90deg
twist=abs(PI/2-twist)
twist=twist*180/PI
torsion_stiffness=M_torsion/1000.0
torsion_stiffness=torsion_stiffness/twist

FINISH
/SOLU

! BRAKING LOADCASE
FDELE,ALL,ALL
F_braking = 4256.0E3/182.5
F,14, FX, -F_braking
F,16, FX, F_braking
SOLVE

/POST1
SET,LAST
*get,max_stress,SECR,ALL,S,EQV,MAX

! Eval weight in kg, without engine beams
ALLS
*GET,weight,ELEM,0,MTOT,Z
weight_engine=3.747881184
weight=weight*1000.0-weight_engine

! Create output file
*CFOPEN,ducati_frame_results,txt
*VWRITE
('### Ducati Frame Results')

*VWRITE,weight
('weight = ',F20.8)

*VWRITE,torsion_stiffness
('torsion_stiffness = ',F20.8)

*VWRITE,max_stress
('max_stress = ',F20.8)

*CFCLOSE

! Alternative to write out all scalar parameters
!PARSAV,SCALAR,'ducati_frame_results','parsav',' '


! SNAPSHOT IMAGE
! --------------
/RESET
ALLS
ESEL,U,SEC,,102
ESEL,U,SEC,,103
EPLOT
/ESHAPE,1
/COLOR,PBAK,0,0
QUALITY,1,0,1,0,0,0
!/VIEW,  1, -0.417114883137    , -0.644625652122    ,  0.640681623657
!/ANG,   1,   41.0870383711
!/LIG,   1,1, 1.000,  0.516358422617    , -0.673953091332    , -0.528357085763    ,  0.124000000000
!/DIST, 1 ,1.082226,1
/DIST, 1 ,1.082226,1
/VIEW,  1, -0.452363751032    , -0.785056420562    ,  0.423147082334
/ANG,   1,   62.3643302729
/LIG,   1,1, 1.000,  0.495872766749    , -0.576245287297    , -0.649654960780    ,  0.124000000000

/SHOW,JPEG,,0
JPEG,QUAL,75,
JPEG,ORIENT,HORIZ
JPEG,COLOR,2
JPEG,TMOD,1
/GFILE,800,

! Image 1
EPLOT

! Image 2
/PNUM,SECT,1
EPLOT

/SHOW,CLOSE

/GO
FINISH
