class Status:

    def gap(self, **kwargs):
        r"""Specifies "mode-superposition transient gap conditions" as the subsequent status topic.

        Mechanical APDL Command: `GAP <https://ansyshelp.ansys.com/Views/Secured/corp/v232/en//ans_cmd/Hlp_C_GAP.html>`_

        Notes
        -----

        .. _GAP_notes:

        This is a status ( :ref:`stat` ) topic command. Status topic commands are generated by the GUI and
        will appear in the log file ( :file:`Jobname.LOG` ) if status is requested for some items under
        Utility Menu> List> Status. This command will be immediately followed by a :ref:`stat` command,
        which will report the status for the specified topic.

        If entered directly into the program, the :ref:`stat` command should immediately follow this
        command.

        .. warning::

            This command is archived in the latest version of the software.

        """
        command = "GAP"
        return self.run(command, **kwargs)


