
name: |
  Test Windows

description: |
  This action runs PyMAPDL tests on Windows

inputs:
  
  # Required inputs

  codecov_token:
    description: |
      Token for Codecov.
    required: true
    type: string

runs:
  using: "composite"
  steps:

    # Skipping because it is installed locally.
    # - name: Setup Python
    #   uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.0.0
    #   with:
    #     python-version: 3.9

    - name: "Checking Python"
      shell: powershell
      run: |
        python -m pip install --upgrade pip

    - name: "Creating python venv"
      shell: powershell
      run: |
        python -m venv .\.venv
        .\.venv\Scripts\activate

    - name: "Install ansys-mapdl-core"
      shell: powershell
      run: |
        python -m pip install build
        python -m build
        $FILE_=Resolve-Path '.\dist\*.whl'
        python -m pip install $FILE_.Path --upgrade
        python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"

    - name: "Unit testing requirements installation"
      shell: powershell
      run: |
        python -m pip install .[tests]

    - name: "Unit testing"
      shell: powershell
      env:
        file_name: windows-v22.2.0-local
        PYTEST_ARGUMENTS: ${{ env.PYTEST_ARGUMENTS }}
      run: |
        set PYMAPDL_PORT=
        set PYMAPDL_START_INSTANCE=
        python -m pytest -k "not test_database and not test_dpf" \
          ${PYTEST_ARGUMENTS} \
          --ignore_image_cache \
          --report-log=$file_name.jsonl \
          --cov-report=xml:$file_name.xml

    - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 #v5.5.1
      name: "Upload coverage to Codecov"
      with:
        token: ${{ inputs.codecov_token }} # required
        name: windows-v22.2.0-local.xml
        flags: windows,local,v22.2.0

    - name: "Upload coverage artifacts"
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: windows-v22.2.0-local.xml
        path: ./windows_local.xml