## To be executed after license server
# 
# You need an env var which points to the docker dpf image:
# 
#        export DPF_DOCKER_IMAGE=ghcr.io/ansys/dpf-core:22.2dev
# 
# As well as the `ANSYSLMD_LICENSE_FILE` env var.
#

services:
  dpf:
    image: ${DPF_DOCKER_IMAGE}
    ports:
      - '50056:50052'
    restart: always
    environment:
      - ANSYSLMD_LICENSE_FILE=${ANSYSLMD_LICENSE_FILE}