version: '3.3'

# DESCRIPTION
# ===========
#
# This docker-compose file extends the 'base' docker-compose file to run the docker in such a way that
# you can then attach your VSCode instance and work locally.
#
# It is said to be running as 'local' because it will mount the current directory in '/local' 
# inside the container (presumably you will have the cloned repository in the current directory),
# and it will override the entrypoint to run the 'bash' command.
#
#
# USAGE
# =====
#
# 1. You need to have the 'base' docker-compose file in the same directory as this file, and fullfil
# its requirements (license server env var).
#
# 2. Once you have done this, you can start the service by running:
#
#      docker-compose -f docker-compose.yml -f docker-compose.local.yml up
#
# NOTES
# =====
#
# - If you need to run a license server, please have a look at 'docker-compose.license_server.yml'
# file. In that case, the command to launch everything is:
# 
#      docker-compose -f docker-compose.yml -f docker-compose.license-server.yml -f docker-compose.local.yml up
#

services:
  mapdl:
    user: "0:0"
    volumes:
      - ../:/local:cached
    # Overwriting entrypoint
    entrypoint: /bin/sh -c "echo 'Container is ready. You can now attach to it.'; while sleep 1000; do :; done"
