"""Script generated by ansys-mapdl-core version 0.60.2"""

from ansys.mapdl.core import launch_mapdl

mapdl = launch_mapdl(loglevel="WARNING")

mapdl.run("/COM,ANSYS MEDIA REL. 150 (11/8/2013) REF. VERIF. MANUAL: REL. 150")

mapdl.run("FINISH")

mapdl.run("/VERIFY,VM10")

mapdl.run("/PREP7")

mapdl.prep7()

mapdl.mp("PRXY", "", 0.3)

mapdl.title("VM10 BENDING OF A TEE SHAPED BEAM")

mapdl.run("C*** MECHANICS OF SOLIDS, CRANDALL AND DAHL, 1959, PAGE 294, EX. 7.2")

mapdl.antype("STATIC")

mapdl.et(1, "BEAM188", "", "", 3)

mapdl.run("SECT,1,BEAM,T")

mapdl.run("SECD,9,20,4,1.5")

mapdl.mp("EX", 1, 30E6)

mapdl.n(1)

mapdl.n(2, 100)

mapdl.n(3, "", 1)

mapdl.e(1, 2, 3)

mapdl.d(1, "ALL")

mapdl.f(2, "MZ", 100000)

mapdl.d("ALL", "UZ", "", "", "", "", "ROTX", "ROTY")

mapdl.finish()

mapdl.run("/SOLU")

mapdl.nsubst(1)

mapdl.outpr("ALL", 1)

mapdl.solve()

mapdl.finish()

mapdl.run("/POST1")

mapdl.etable("STRS_B", "LS", 1)

mapdl.etable("STRS_T", "LS", 31)

mapdl.get("STRSS_B", "ELEM", 1, "ETAB", "STRS_B")

mapdl.get("STRSS_T", "ELEM", 1, "ETAB", "STRS_T")

mapdl.run("*DIM,LABEL,CHAR,2,2")

mapdl.run("*DIM,VALUE,,2,3")

mapdl.run("LABEL(1,1) = 'STRSS,(B','STRSS,(T'")

mapdl.run("LABEL(1,2) = 'OT) psi ','OP) psi '")

mapdl.run("*VFILL,VALUE(1,1),DATA,300,-700")

mapdl.run("*VFILL,VALUE(1,2),DATA,STRSS_B,STRSS_T")

mapdl.run("*VFILL,VALUE(1,3),DATA,ABS(STRSS_B/300) ,ABS(STRSS_T/700 )")

mapdl.run("/COM")

with mapdl.non_interactive:

    mapdl.run("/OUT,vm10,vrt")

    mapdl.run("/COM,------------------- VM10 RESULTS COMPARISON ---------------------")

    mapdl.run("/COM,")

    mapdl.run("/COM, | TARGET | Mechanical APDL | RATIO")

    mapdl.run("/COM,")

    mapdl.run("*VWRITE,LABEL(1,1),LABEL(1,2),VALUE(1,1),VALUE(1,2),VALUE(1,3)")

    mapdl.run("(1X,A8,A8,' ',F10.0,' ',F10.0,' ',1F5.3)")

    mapdl.run("/COM,-----------------------------------------------------------------")

mapdl.run("/OUT")

mapdl.run("/GOPR")

mapdl.finish()

mapdl.run("*LIST,vm10,vrt")

mapdl.exit()