# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.grpc.mapdl import ansys_kernel_pb2 as ansys__kernel__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ansys.mapdl.core import mapdl_db_pb2 as mapdl__db__pb2

class MapdlDbServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NodNext = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodNext',
        request_serializer=mapdl__db__pb2.NodRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodResponse.FromString,
        )
    self.NodPrev = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodPrev',
        request_serializer=mapdl__db__pb2.NodRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodResponse.FromString,
        )
    self.NodNextDefined = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodNextDefined',
        request_serializer=mapdl__db__pb2.NodRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodResponse.FromString,
        )
    self.NodSel = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodSel',
        request_serializer=mapdl__db__pb2.NodSelRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ElmNext = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmNext',
        request_serializer=mapdl__db__pb2.ElmRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmResponse.FromString,
        )
    self.ElmPrev = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmPrev',
        request_serializer=mapdl__db__pb2.ElmRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmResponse.FromString,
        )
    self.ElmNextDefined = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmNextDefined',
        request_serializer=mapdl__db__pb2.ElmRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmResponse.FromString,
        )
    self.ElmSel = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmSel',
        request_serializer=mapdl__db__pb2.ElmSelRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.NodInqr = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodInqr',
        request_serializer=mapdl__db__pb2.NodInqrRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodInqrResponse.FromString,
        )
    self.getNod = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getNod',
        request_serializer=mapdl__db__pb2.getnodRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getnodResponse.FromString,
        )
    self.putNod = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putNod',
        request_serializer=mapdl__db__pb2.putnodRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.getAllNod = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllNod',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getnodResponse.FromString,
        )
    self.getAllNodC = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllNodC',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.Chunk.FromString,
        )
    self.putAllNod = channel.stream_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putAllNod',
        request_serializer=mapdl__db__pb2.putnodRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.NodGall = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodGall',
        request_serializer=mapdl__db__pb2.NodGallRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodGallResponse.FromString,
        )
    self.NodSpgt = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodSpgt',
        request_serializer=mapdl__db__pb2.NodSpgtRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodSpgtResponse.FromString,
        )
    self.ElmIqr = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmIqr',
        request_serializer=mapdl__db__pb2.ElmIqrRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmIqrResponse.FromString,
        )
    self.getElm = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getElm',
        request_serializer=mapdl__db__pb2.getelmRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getelmResponse.FromString,
        )
    self.putElm = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putElm',
        request_serializer=mapdl__db__pb2.putelmRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.getAllElm = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllElm',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getelmResponse.FromString,
        )
    self.getAllElmC = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllElmC',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.Chunk.FromString,
        )
    self.putAllElm = channel.stream_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putAllElm',
        request_serializer=mapdl__db__pb2.putelmRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.iqrEty = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/iqrEty',
        request_serializer=mapdl__db__pb2.iqretyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.iqretyResponse.FromString,
        )
    self.getEty = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getEty',
        request_serializer=mapdl__db__pb2.getetyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getetyResponse.FromString,
        )
    self.putEty = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putEty',
        request_serializer=mapdl__db__pb2.putetyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.getAllEty = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllEty',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getetyResponse.FromString,
        )
    self.getAllEtyC = channel.unary_stream(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getAllEtyC',
        request_serializer=ansys__kernel__pb2.EmptyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.Chunk.FromString,
        )
    self.putAllEty = channel.stream_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putAllEty',
        request_serializer=mapdl__db__pb2.putetyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.iqrMp = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/iqrMp',
        request_serializer=mapdl__db__pb2.iqrmpRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.iqrmpResponse.FromString,
        )
    self.getMp = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getMp',
        request_serializer=mapdl__db__pb2.getmpRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getmpResponse.FromString,
        )
    self.putMp = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putMp',
        request_serializer=mapdl__db__pb2.putmpRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.delMp = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/delMp',
        request_serializer=mapdl__db__pb2.getmpRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.iqrCsy = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/iqrCsy',
        request_serializer=mapdl__db__pb2.iqrcsyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.iqrcsyResponse.FromString,
        )
    self.getCsy = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getCsy',
        request_serializer=mapdl__db__pb2.getcsyRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.getcsyResponse.FromString,
        )
    self.putCsy = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putCsy',
        request_serializer=mapdl__db__pb2.putcsyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.delCsy = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/delCsy',
        request_serializer=mapdl__db__pb2.getcsyRequest.SerializeToString,
        response_deserializer=ansys__kernel__pb2.EmptyResponse.FromString,
        )
    self.NodResIqr = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodResIqr',
        request_serializer=mapdl__db__pb2.NodResIqrRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodResIqrResponse.FromString,
        )
    self.NodResGet = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodResGet',
        request_serializer=mapdl__db__pb2.NodResGetRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.NodResGetResponse.FromString,
        )
    self.NodResPut = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodResPut',
        request_serializer=mapdl__db__pb2.NodResPutRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.NodResDel = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/NodResDel',
        request_serializer=mapdl__db__pb2.NodResDelRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ElmResIqr = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmResIqr',
        request_serializer=mapdl__db__pb2.ElmResIqrRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmResIqrResponse.FromString,
        )
    self.ElmResGet = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmResGet',
        request_serializer=mapdl__db__pb2.ElmResGetRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.ElmResGetResponse.FromString,
        )
    self.ElmResPut = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmResPut',
        request_serializer=mapdl__db__pb2.ElmResPutRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ElmResDel = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/ElmResDel',
        request_serializer=mapdl__db__pb2.ElmResDelRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getElmInfo = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getElmInfo',
        request_serializer=mapdl__db__pb2.GetElmInfoRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.GetElmInfoResponse.FromString,
        )
    self.getElmData = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/getElmData',
        request_serializer=mapdl__db__pb2.GetElmDataRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.GetElmDataResponse.FromString,
        )
    self.putElmData = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putElmData',
        request_serializer=mapdl__db__pb2.PutElmDataRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.PutElmDataResponse.FromString,
        )
    self.putElmMatRec1 = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/putElmMatRec1',
        request_serializer=mapdl__db__pb2.putElmMatRec1Request.SerializeToString,
        response_deserializer=mapdl__db__pb2.putElmMatRec1Response.FromString,
        )
    self.INISIsNewVersionUsed = channel.unary_unary(
        '/ansys.api.mapdl_db.v0.MapdlDbService/INISIsNewVersionUsed',
        request_serializer=mapdl__db__pb2.INISIsNewVersionUsedRequest.SerializeToString,
        response_deserializer=mapdl__db__pb2.INISIsNewVersionUsedResponse.FromString,
        )


class MapdlDbServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def NodNext(self, request, context):
    """Get Next Node Number -				ndnext  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodPrev(self, request, context):
    """Get Prev Node Number -				ndprev  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodNextDefined(self, request, context):
    """Get Number of the Next Defined Node -		ndnxdf  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodSel(self, request, context):
    """Select, Unselect, Delete or Invert a Node -  	ndsel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmNext(self, request, context):
    """Get the Number of the Next Element -		        elnext
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmPrev(self, request, context):
    """Get the Number of the Prev Element -		        elprev  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmNextDefined(self, request, context):
    """Get the Number of the Next Defined Element -	        elnxdf  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmSel(self, request, context):
    """Select, Unselect, Delete or Invert an Element -	elsel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodInqr(self, request, context):
    """Get Information about a Node -			ndinqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getNod(self, request, context):
    """Get a Nodal Point -				        getnod
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putNod(self, request, context):
    """Storing a Node -					putnod
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllNod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllNodC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putAllNod(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodGall(self, request, context):
    """Get XYZ/Rotation Coordinates Vector for a Node -	ndgall
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodSpgt(self, request, context):
    """Get the Nodal Solution for a Node of an Element -	ndspgt
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmIqr(self, request, context):
    """Get Information about an Element -			elmiqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getElm(self, request, context):
    """Get an Element's Attributes and Nodes -		elmget
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putElm(self, request, context):
    """Storing an Element -					elmput
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllElm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllElmC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putAllElm(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def iqrEty(self, request, context):
    """Get a Data Item about an Element Type -	etyiqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getEty(self, request, context):
    """Get Information about an Element Type -	etyget
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putEty(self, request, context):
    """Storing Element Type Data -			etyput
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllEty(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAllEtyC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putAllEty(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def iqrMp(self, request, context):
    """Get Information about Element Characteristics -	echrtr
    Select, Unselect, Delete or Invert an Elem Type -	etysel

    Get Information about an Material Property -	mpinqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMp(self, request, context):
    """Get a Material Property Table -		mpget
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putMp(self, request, context):
    """Storing a Material Property Table -		mpput
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delMp(self, request, context):
    """Delete a Material Property Table -		mpdel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def iqrCsy(self, request, context):
    """Get Information about a Real Constant Set -	rlinqr
    Get Real Constant Data -				rlget
    Select or Delete a Real Constant Set -		rlsel

    Get Information about a Coordinate System -	csyiqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCsy(self, request, context):
    """Get a Coordinate System -			csyget
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putCsy(self, request, context):
    """Store a Coordinate System -			csyput
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delCsy(self, request, context):
    """Delete a Coordinate System -			csydel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodResIqr(self, request, context):
    """Get Information about a coupled Set -		cpinqr
    Get a coupled Set -				cpget
    Store a coupled Set -				cpput
    Select / Delete a couple Set -			cpsel

    Get Information about a Constraint Eq. Set -	ceinqr
    Get a Constaint Equation -				ceget
    Store a Constaint Equation -			ceput
    Delete / Select a Constaint Equation -		cesel

    Get Information about Constaints -			disiqr
    Get a Constaint at a Node -			disget
    Store a Constraint at a Node -			disput
    Delete a Constraint at a Node -			disdel

    Get Information about Nodal Loads -		foriqr
    Get a Nodal Load at a Node -			forget
    Store a Nodal Load at a Node -			forput
    Delete a nodal Load at a Node -			fordel

    Get Info about a Nodal Body Load -			ansNodeBodyLoadlqr
    Get a Nodal Body Load Value -			ansNodeBodyLoadGet
    Store a Nodal Body Load -				ansNodeBodyLoadPut
    Delete a Nodal Body Load -				ansNodeBodyLoadDel

    Get Info about a Element Body Load -		ansElemBodyLoadlqr
    Get a Elem Body Load Value -			ansElemBodyLoadGet
    Store a Elem Body Load -				ansElemBodyLoadPut
    Delete a Elem Body Load -				ansElemBodyLoadDel

    Get Info about a Elem Surface Load -		ansElemSurfLoadlqr
    Get a Elem Surface Load Value -			ansElemSurfLoadGet
    Store a Elem Surface Load -			ansElemSurfLoadPut
    Delete a Elem Surface Load -			ansElemSurfLoadDel

    Nodal Results API

    Get Information about Nodal Results -		dspiqr
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodResGet(self, request, context):
    """Get a Nodal Result from the DB -			dspget  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodResPut(self, request, context):
    """Store a Result at a Node -				dspput  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NodResDel(self, request, context):
    """Delete a Result at a Node -			        dsldel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmResIqr(self, request, context):
    """Element Results API

    Get Information about Element Results -		iqr  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmResGet(self, request, context):
    """Get an Element Result from the DB -		        get  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmResPut(self, request, context):
    """Store a Result at an Element -			put  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ElmResDel(self, request, context):
    """Delete a Result at an Element -			del
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getElmInfo(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getElmData(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putElmData(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putElmMatRec1(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def INISIsNewVersionUsed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MapdlDbServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NodNext': grpc.unary_unary_rpc_method_handler(
          servicer.NodNext,
          request_deserializer=mapdl__db__pb2.NodRequest.FromString,
          response_serializer=mapdl__db__pb2.NodResponse.SerializeToString,
      ),
      'NodPrev': grpc.unary_unary_rpc_method_handler(
          servicer.NodPrev,
          request_deserializer=mapdl__db__pb2.NodRequest.FromString,
          response_serializer=mapdl__db__pb2.NodResponse.SerializeToString,
      ),
      'NodNextDefined': grpc.unary_unary_rpc_method_handler(
          servicer.NodNextDefined,
          request_deserializer=mapdl__db__pb2.NodRequest.FromString,
          response_serializer=mapdl__db__pb2.NodResponse.SerializeToString,
      ),
      'NodSel': grpc.unary_unary_rpc_method_handler(
          servicer.NodSel,
          request_deserializer=mapdl__db__pb2.NodSelRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ElmNext': grpc.unary_unary_rpc_method_handler(
          servicer.ElmNext,
          request_deserializer=mapdl__db__pb2.ElmRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmResponse.SerializeToString,
      ),
      'ElmPrev': grpc.unary_unary_rpc_method_handler(
          servicer.ElmPrev,
          request_deserializer=mapdl__db__pb2.ElmRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmResponse.SerializeToString,
      ),
      'ElmNextDefined': grpc.unary_unary_rpc_method_handler(
          servicer.ElmNextDefined,
          request_deserializer=mapdl__db__pb2.ElmRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmResponse.SerializeToString,
      ),
      'ElmSel': grpc.unary_unary_rpc_method_handler(
          servicer.ElmSel,
          request_deserializer=mapdl__db__pb2.ElmSelRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'NodInqr': grpc.unary_unary_rpc_method_handler(
          servicer.NodInqr,
          request_deserializer=mapdl__db__pb2.NodInqrRequest.FromString,
          response_serializer=mapdl__db__pb2.NodInqrResponse.SerializeToString,
      ),
      'getNod': grpc.unary_unary_rpc_method_handler(
          servicer.getNod,
          request_deserializer=mapdl__db__pb2.getnodRequest.FromString,
          response_serializer=mapdl__db__pb2.getnodResponse.SerializeToString,
      ),
      'putNod': grpc.unary_unary_rpc_method_handler(
          servicer.putNod,
          request_deserializer=mapdl__db__pb2.putnodRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'getAllNod': grpc.unary_stream_rpc_method_handler(
          servicer.getAllNod,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=mapdl__db__pb2.getnodResponse.SerializeToString,
      ),
      'getAllNodC': grpc.unary_stream_rpc_method_handler(
          servicer.getAllNodC,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=ansys__kernel__pb2.Chunk.SerializeToString,
      ),
      'putAllNod': grpc.stream_unary_rpc_method_handler(
          servicer.putAllNod,
          request_deserializer=mapdl__db__pb2.putnodRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'NodGall': grpc.unary_unary_rpc_method_handler(
          servicer.NodGall,
          request_deserializer=mapdl__db__pb2.NodGallRequest.FromString,
          response_serializer=mapdl__db__pb2.NodGallResponse.SerializeToString,
      ),
      'NodSpgt': grpc.unary_unary_rpc_method_handler(
          servicer.NodSpgt,
          request_deserializer=mapdl__db__pb2.NodSpgtRequest.FromString,
          response_serializer=mapdl__db__pb2.NodSpgtResponse.SerializeToString,
      ),
      'ElmIqr': grpc.unary_unary_rpc_method_handler(
          servicer.ElmIqr,
          request_deserializer=mapdl__db__pb2.ElmIqrRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmIqrResponse.SerializeToString,
      ),
      'getElm': grpc.unary_unary_rpc_method_handler(
          servicer.getElm,
          request_deserializer=mapdl__db__pb2.getelmRequest.FromString,
          response_serializer=mapdl__db__pb2.getelmResponse.SerializeToString,
      ),
      'putElm': grpc.unary_unary_rpc_method_handler(
          servicer.putElm,
          request_deserializer=mapdl__db__pb2.putelmRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'getAllElm': grpc.unary_stream_rpc_method_handler(
          servicer.getAllElm,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=mapdl__db__pb2.getelmResponse.SerializeToString,
      ),
      'getAllElmC': grpc.unary_stream_rpc_method_handler(
          servicer.getAllElmC,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=ansys__kernel__pb2.Chunk.SerializeToString,
      ),
      'putAllElm': grpc.stream_unary_rpc_method_handler(
          servicer.putAllElm,
          request_deserializer=mapdl__db__pb2.putelmRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'iqrEty': grpc.unary_unary_rpc_method_handler(
          servicer.iqrEty,
          request_deserializer=mapdl__db__pb2.iqretyRequest.FromString,
          response_serializer=mapdl__db__pb2.iqretyResponse.SerializeToString,
      ),
      'getEty': grpc.unary_unary_rpc_method_handler(
          servicer.getEty,
          request_deserializer=mapdl__db__pb2.getetyRequest.FromString,
          response_serializer=mapdl__db__pb2.getetyResponse.SerializeToString,
      ),
      'putEty': grpc.unary_unary_rpc_method_handler(
          servicer.putEty,
          request_deserializer=mapdl__db__pb2.putetyRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'getAllEty': grpc.unary_stream_rpc_method_handler(
          servicer.getAllEty,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=mapdl__db__pb2.getetyResponse.SerializeToString,
      ),
      'getAllEtyC': grpc.unary_stream_rpc_method_handler(
          servicer.getAllEtyC,
          request_deserializer=ansys__kernel__pb2.EmptyRequest.FromString,
          response_serializer=ansys__kernel__pb2.Chunk.SerializeToString,
      ),
      'putAllEty': grpc.stream_unary_rpc_method_handler(
          servicer.putAllEty,
          request_deserializer=mapdl__db__pb2.putetyRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'iqrMp': grpc.unary_unary_rpc_method_handler(
          servicer.iqrMp,
          request_deserializer=mapdl__db__pb2.iqrmpRequest.FromString,
          response_serializer=mapdl__db__pb2.iqrmpResponse.SerializeToString,
      ),
      'getMp': grpc.unary_unary_rpc_method_handler(
          servicer.getMp,
          request_deserializer=mapdl__db__pb2.getmpRequest.FromString,
          response_serializer=mapdl__db__pb2.getmpResponse.SerializeToString,
      ),
      'putMp': grpc.unary_unary_rpc_method_handler(
          servicer.putMp,
          request_deserializer=mapdl__db__pb2.putmpRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'delMp': grpc.unary_unary_rpc_method_handler(
          servicer.delMp,
          request_deserializer=mapdl__db__pb2.getmpRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'iqrCsy': grpc.unary_unary_rpc_method_handler(
          servicer.iqrCsy,
          request_deserializer=mapdl__db__pb2.iqrcsyRequest.FromString,
          response_serializer=mapdl__db__pb2.iqrcsyResponse.SerializeToString,
      ),
      'getCsy': grpc.unary_unary_rpc_method_handler(
          servicer.getCsy,
          request_deserializer=mapdl__db__pb2.getcsyRequest.FromString,
          response_serializer=mapdl__db__pb2.getcsyResponse.SerializeToString,
      ),
      'putCsy': grpc.unary_unary_rpc_method_handler(
          servicer.putCsy,
          request_deserializer=mapdl__db__pb2.putcsyRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'delCsy': grpc.unary_unary_rpc_method_handler(
          servicer.delCsy,
          request_deserializer=mapdl__db__pb2.getcsyRequest.FromString,
          response_serializer=ansys__kernel__pb2.EmptyResponse.SerializeToString,
      ),
      'NodResIqr': grpc.unary_unary_rpc_method_handler(
          servicer.NodResIqr,
          request_deserializer=mapdl__db__pb2.NodResIqrRequest.FromString,
          response_serializer=mapdl__db__pb2.NodResIqrResponse.SerializeToString,
      ),
      'NodResGet': grpc.unary_unary_rpc_method_handler(
          servicer.NodResGet,
          request_deserializer=mapdl__db__pb2.NodResGetRequest.FromString,
          response_serializer=mapdl__db__pb2.NodResGetResponse.SerializeToString,
      ),
      'NodResPut': grpc.unary_unary_rpc_method_handler(
          servicer.NodResPut,
          request_deserializer=mapdl__db__pb2.NodResPutRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'NodResDel': grpc.unary_unary_rpc_method_handler(
          servicer.NodResDel,
          request_deserializer=mapdl__db__pb2.NodResDelRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ElmResIqr': grpc.unary_unary_rpc_method_handler(
          servicer.ElmResIqr,
          request_deserializer=mapdl__db__pb2.ElmResIqrRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmResIqrResponse.SerializeToString,
      ),
      'ElmResGet': grpc.unary_unary_rpc_method_handler(
          servicer.ElmResGet,
          request_deserializer=mapdl__db__pb2.ElmResGetRequest.FromString,
          response_serializer=mapdl__db__pb2.ElmResGetResponse.SerializeToString,
      ),
      'ElmResPut': grpc.unary_unary_rpc_method_handler(
          servicer.ElmResPut,
          request_deserializer=mapdl__db__pb2.ElmResPutRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ElmResDel': grpc.unary_unary_rpc_method_handler(
          servicer.ElmResDel,
          request_deserializer=mapdl__db__pb2.ElmResDelRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getElmInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getElmInfo,
          request_deserializer=mapdl__db__pb2.GetElmInfoRequest.FromString,
          response_serializer=mapdl__db__pb2.GetElmInfoResponse.SerializeToString,
      ),
      'getElmData': grpc.unary_unary_rpc_method_handler(
          servicer.getElmData,
          request_deserializer=mapdl__db__pb2.GetElmDataRequest.FromString,
          response_serializer=mapdl__db__pb2.GetElmDataResponse.SerializeToString,
      ),
      'putElmData': grpc.unary_unary_rpc_method_handler(
          servicer.putElmData,
          request_deserializer=mapdl__db__pb2.PutElmDataRequest.FromString,
          response_serializer=mapdl__db__pb2.PutElmDataResponse.SerializeToString,
      ),
      'putElmMatRec1': grpc.unary_unary_rpc_method_handler(
          servicer.putElmMatRec1,
          request_deserializer=mapdl__db__pb2.putElmMatRec1Request.FromString,
          response_serializer=mapdl__db__pb2.putElmMatRec1Response.SerializeToString,
      ),
      'INISIsNewVersionUsed': grpc.unary_unary_rpc_method_handler(
          servicer.INISIsNewVersionUsed,
          request_deserializer=mapdl__db__pb2.INISIsNewVersionUsedRequest.FromString,
          response_serializer=mapdl__db__pb2.INISIsNewVersionUsedResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.mapdl_db.v0.MapdlDbService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
