name: Docker images - Cleanup
on:
  workflow_dispatch:
  schedule: # UTC at 0200
    - cron: "0 2 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup:
    name: Cleaning unnecessary packages
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed to read repository contents
      packages: write  # Needed to delete untagged Docker images
    env:
      PACKAGE_DELETION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - name: "Perform versions cleanup - except certain tags"
      uses: ansys/actions/hk-package-clean-untagged@d98e1a4008dab392f8c114a483c2c5624076ccd6 #v11.0.1
      with:
        package-name: 'mapdl'
        token: ${{ secrets.GITHUB_TOKEN }}
        allow-last-days: 5
