name: Merge to main

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  DOCUMENTATION_CNAME: 'mapdl.docs.pyansys.com'

jobs:
  upload_dev_docs:
    name: 'Upload dev documentation'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the latest documentation
        uses: pyansys/actions/doc-deploy-dev@v2.0.8
        with:        
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          commit: ${{github.event.pull.before}}

  update_coverage:
    name: 'Update coverage report'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Download the previously generated coverage reports'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          commit: ${{github.event.pull.before}}
          path: ./artifacts
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: "Display files structure"
        if: always()
        run: |
          echo "::group:: Display files structure" && ls -R && echo "::endgroup::"

      - uses: codecov/codecov-action@v3
        name: "Upload coverage to Codecov"
        with:
          directory: ./artifacts/



