# check spelling, codestyle
name: Style Check

on:
  push:
    branches-ignore:
      # Push events to branches matching refs/heads/mona/octocat
      - 'gh-pages'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Style
        run: |
          pip install -r requirements_style.txt --disable-pip-version-check
          make
